cargo-features = ["edition2021", "strip"]

[package]
name = "sherlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
rayon = "1.5.1"
colored = "2.0.0"

[profile.release]
opt-level = "s"
debug = 0
overflow-checks = false
strip = "symbols"
lto = "fat"
panic = "abort"