cargo-features = ["strip"]

[package]
name = "watson"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
rayon = "1.5.1"
colored = "2.0.0"
async-trait = "0.1.51"
futures = "0.3.17"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = "s"
debug = 0
overflow-checks = false
strip = "symbols"
lto = "fat"
panic = "abort"